### ISSUE TITLE
Bug with left/right position usage

### ISSUE THREAD

**Issue by demery** [leoba/VisColl#9]
In the referenced code `leftFolioFilename` and `rightFolioFilename` both use `$bi1`, but above separate left and right variables are created `$bi1` and `$bi2`:

```xsl
                            <xsl:variable name="bi1" select="inside/left/leaf/vc:q/@position"/>
                            <xsl:variable name="bi2" select="inside/right/leaf/vc:q/@position"/>
```

Is the duplicated use of `bi1` a bug?

https://github.com/KislakCenter/VisColl/blob/a993930f9c4d8afbfbc161f5d205620e9c2d815d/data/xslt/viscoll_mod2_processed-XML_to_HTML.xsl#L377-L390

**Comment by acampagnolo** [comment]
Resolved the bug and pushed
